# Generated by Django 4.0.2 on 2022-02-19 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receivers', '0002_receiver_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receiver',
            old_name='adress',
            new_name='address',
        ),
    ]
