# Generated by Django 4.0.2 on 2022-02-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receivers', '0003_rename_adress_receiver_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiver',
            name='logo',
            field=models.ImageField(default='images/no_photo.png', upload_to=''),
        ),
    ]
